codecov:
  token: 55f60f3b-5cf1-4e6a-a98b-6f32bc840b7b

coverage:
  status:
    project: false
    patch: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        informational: true
      - type: patch
        informational: true
  individual_flags:
    - name: backend
      paths:
        - cmd/
        - pkg/
        - server/
        - ee/
        - orbit/
    - name: frontend
      paths:
        - frontend/
