name: Check for bad links in documentation

on:
  pull_request:
    paths:
    # Only run on changes to .md files -- this check is too flakey to run on every PR
    - '**.md'
  workflow_dispatch: # Manual
  schedule:
  - cron: '0 6 * * *' # Nightly 6AM UTC

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  markdown-link-check:
    permissions:
      contents: read # to read files to check dead links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # master
    - uses: gaurav-nelson/github-action-markdown-link-check@58f84fd654812d0d8da4e4d4a559eda087daf8ce # v1.0.13
      with:
        use-quiet-mode: 'yes'
        config-file: .github/workflows/config/markdown-link-check-config.json
        base-branch: ${{ github.base_ref }}
