name: Test yml specs

on:
  push:
    branches:
      - main
      - patch-*
    paths:
      - 'ee/cis/**.yml'
      - '.github/workflows/test-yml-specs.yml'
  pull_request:
    paths:
      - 'ee/cis/**.yml'
      - '.github/workflows/test-yml-specs.yml'
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-yml-specs:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ['^1.19.8']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v2

    - name: Run apply spec tests
      run: |
        go test -v ./pkg/spec/...