name: tfvalidate

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  workflow_dispatch: # Manual dispatch

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  tfvalidate:
    name: terraform validate
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install terraform
        uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867 # v2.0.0
        with:
          terraform_version: 1.3.0

      - name: Validate loadtesting
        working-directory: ./infrastructure/loadtesting/terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validate infrastructure
        working-directory: ./infrastructure/infrastructure/terraform
        run: |
          terraform init -backend=false
          terraform validate
